### ISSUE TITLE
Need a way to download .items files

### ISSUE THREAD

**Issue by Giannie** [mscroggs/AVE-website#5]
The badge needs to have a separate .items file that contains the items. It's ok if the ave file also contains the items, but it speeds up if we also have a separate .items file.

It would be good to have a mechanism to generate these server side as it is very slow to do it on the badge.

**Comment by mscroggs** [comment]
I'll add these at avegame.co.uk/download/NAME.items

Probably have time for this this evening...

**Comment by mscroggs** [comment]
Fixed. See http://avegame.co.uk/docs/website.md for documentation on website
